theme: jekyll-theme-minimal
title: Caitriona Devery
description: This is my site, and this is the description of my site.
logo: logo.jpeg
github:
  is_project_page: false
  is_user_page: false
pages:
  - title: "Portfolio"
    url: "portfolio.html"